version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/Pizza
    overwrite: yes

permission:
  - object: /home/ubuntu/Pizza
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  ApplicationStart:
    - location: scripts/gh_deploy.sh
      timeout: 60
      runas: ubuntu